# Generated by Django 4.2.6 on 2023-10-20 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
